// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectPokemon.Pokedex.Views.Gen7.Pokemon
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Details : DetailsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"<div class=""row"">
	<div class=""col-md-3"">
		<div class=""pkm-image-inner"" style=""text-align:center;"">
			<div data-role='commentContent' class='ipsType_normal ipsType_richText ipsContained' data-controller='core.front.core.lightboxedImages'>
				<p>
					");
            
            #line 12 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.GetIsAltForm()) {
						var originalForm = Model.Data.Pokemon[Model.GetOriginalFormId().Value];
						
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<img class=\"ipsImage\" src=\"https://projectpokemon.org/images/sugimori/");
            
            #line 15 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(originalForm.ID));
            
            #line default
            #line hidden
            this.Write("-");
            
            #line 15 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.GetFormName().ToLower().Replace(' ', '-')));
            
            #line default
            #line hidden
            this.Write(".png\" alt=\"");
            
            #line 15 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" Sugimori Artwork\" />\r\n\t\t\t\t\t");
            
            #line 16 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<img class=\"ipsImage\" src=\"https://projectpokemon.org/images/sugimori/");
            
            #line 17 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ID));
            
            #line default
            #line hidden
            this.Write(".png\" alt=\"");
            
            #line 17 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write(" Sugimori Artwork\" />\r\n\t\t\t\t\t");
            
            #line 18 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</p>\t\t\t\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t");
            
            #line 22 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.GetIsAltForm()) {
			var originalForm = Model.Data.Pokemon[Model.GetOriginalFormId().Value];
			
            
            #line default
            #line hidden
            this.Write("\t\t\t<a href=\"https://projectpokemon.org/home/gallery/album/");
            
            #line 25 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((originalForm.ID + 1).ToString()));
            
            #line default
            #line hidden
            this.Write("-");
            
            #line 25 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(originalForm.ID.ToString().PadLeft(3, '0')));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 25 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(originalForm.Name));
            
            #line default
            #line hidden
            this.Write("/\">See more images</a>\r\n\t\t");
            
            #line 26 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<a href=\"https://projectpokemon.org/home/gallery/album/");
            
            #line 27 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((Model.ID + 1).ToString()));
            
            #line default
            #line hidden
            this.Write("-");
            
            #line 27 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ID.ToString().PadLeft(3, '0')));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 27 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("/\">See more images</a>\r\n\t\t");
            
            #line 28 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t</div>\r\n\r\n\t<div class=\"col-md-6\">\r\n\t\t<h2>Pokédex</h2>\r\n\t\t<table class=\"table\">\r\n" +
                    "\t\t\t<tr>\r\n\t\t\t\t<td style=\"width: 50%;\">\r\n\t\t\t\t\tName\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 39 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tCategory\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t" +
                    "\t\t");
            
            #line 47 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Classification));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 52 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Type2.ID > 0 && Model.Type1.ID != Model.Type2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tTypes\r\n\t\t\t\t\t");
            
            #line 54 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tType\r\n\t\t\t\t\t");
            
            #line 56 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$idPrefix-type-");
            
            #line 59 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 59 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type1.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 59 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type1.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t\t");
            
            #line 60 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Type2.ID > 0 && Model.Type1.ID != Model.Type2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<a href=\"{page=\"$idPrefix-type-");
            
            #line 61 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 61 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type2.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 61 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type2.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t\t");
            
            #line 62 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</td>\t\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 67 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Ability1.ID == Model.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tAbility\r\n\t\t\t\t\t");
            
            #line 69 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tAbilities\r\n\t\t\t\t\t");
            
            #line 71 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$idPrefix-ability-");
            
            #line 74 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 74 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability1.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\r\n\t\t\t\t\t");
            
            #line 76 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Ability1.ID != Model.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<a href=\"{page=\"$idPrefix-ability-");
            
            #line 77 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 77 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability2.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t\t");
            
            #line 78 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</td>\r\n\t\t\t</tr>\t\t\t\r\n\t\t\t");
            
            #line 81 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.AbilityHidden.ID != Model.Ability1.ID && Model.AbilityHidden.ID != Model.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tHidden Ability\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=" +
                    "\"$idPrefix-ability-");
            
            #line 87 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AbilityHidden.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 87 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AbilityHidden.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 90 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 91 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (!string.IsNullOrEmpty(Model.PokedexTextSun) && Model.PokedexTextSun == Model.PokedexTextMoon) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\tDescription\r\n\t\t\t\t\t</td>\r\n\t\t\t\t\t<td>\r\n\t\t\t\t\t\t");
            
            #line 97 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PokedexTextSun.Replace("\\n", "<br />")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t");
            
            #line 100 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 101 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (!string.IsNullOrEmpty(Model.PokedexTextSun)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\tDescription (Sun)\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\t" +
                    "");
            
            #line 107 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PokedexTextSun.Replace("\\n", "<br />")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t");
            
            #line 110 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 111 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (!string.IsNullOrEmpty(Model.PokedexTextMoon)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t\tDescription (Moon)\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t\t<td>\r\n\t\t\t\t\t\t" +
                    "\t");
            
            #line 117 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PokedexTextMoon.Replace("\\n", "<br />")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t</td>\r\n\t\t\t\t\t</tr>\r\n\t\t\t\t");
            
            #line 120 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 121 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tHeight\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 127 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 var feet = Model.Height * (decimal)3.2808399; 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t");
            
            #line 128 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Height));
            
            #line default
            #line hidden
            this.Write(" m (");
            
            #line 128 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Math.Floor(feet).ToString()));
            
            #line default
            #line hidden
            this.Write("\'");
            
            #line 128 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((feet - Math.Floor(feet)) * 12).ToString("0")));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tWeight\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t" +
                    "\t\t");
            
            #line 136 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Weight));
            
            #line default
            #line hidden
            this.Write(" kg (");
            
            #line 136 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((Model.Weight * (decimal)2.20462262).ToString("0.0")));
            
            #line default
            #line hidden
            this.Write(" lbs.)\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tGender\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r" +
                    "\n\t\t\t\t\t");
            
            #line 144 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Gender == 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tAll Male\r\n\t\t\t\t\t");
            
            #line 146 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else if (Model.Gender == 254) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tAll Female\r\n\t\t\t\t\t");
            
            #line 148 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else if (Model.Gender == 255) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\tGenderless\r\n\t\t\t\t\t");
            
            #line 150 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t");
            
            #line 151 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture((1 - ((Model.Gender - 1) / (decimal)252)).ToString("P")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t<span style=\"color: blue;\">&#9794;</span>\r\n\t\t\t\t\t\t");
            
            #line 153 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(((Model.Gender - 1) / (decimal)252).ToString("P")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t\t<span style=\"color: magenta;\">&#9792;</span>\r\n\t\t\t\t\t");
            
            #line 155 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\r\n\t\t\t\t</td>\t\t\t\t\r\n\t\t\t</tr>\r\n\t\t\t<tr>\t\t\t\t\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 160 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.EggGroup1 != Model.EggGroup2) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tEgg Groups\r\n\t\t\t\t\t");
            
            #line 162 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tEgg Group\r\n\t\t\t\t\t");
            
            #line 164 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 167 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EggGroup1));
            
            #line default
            #line hidden
            this.Write(" \r\n\t\t\t\t\t");
            
            #line 168 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.EggGroup1 != Model.EggGroup2) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br />");
            
            #line 169 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EggGroup2));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t");
            
            #line 170 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t</table>\r\n\t\t<h2>Details</h2>\r\n\t\t<table class=\"table\">\t\t\t\r\n" +
                    "\t\t\t<tr>\r\n\t\t\t\t<td style=\"width: 50%;\">\r\n\t\t\t\t\tCatch Rate\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t" +
                    "\t\t");
            
            #line 181 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CatchRate));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tEvo Stage\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t" +
                    "\t\t\t");
            
            #line 189 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EvoStage));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 192 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.HeldItem1.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tHeld Item 1\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$i" +
                    "dPrefix-item-");
            
            #line 198 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 198 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem1.Name));
            
            #line default
            #line hidden
            this.Write("</a> (50%)\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 201 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 203 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.HeldItem2.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tHeld Item 2\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$i" +
                    "dPrefix-item-");
            
            #line 209 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 209 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem2.Name));
            
            #line default
            #line hidden
            this.Write("</a> (5%)\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 212 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 213 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.HeldItem3.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tHeld Item 3\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$" +
                    "idPrefix-item-");
            
            #line 219 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem3.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 219 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem3.Name));
            
            #line default
            #line hidden
            this.Write("</a> (1%)\r\n\t\t\t\t</td>\r\n\t\t\t\t</tr>\r\n\t\t\t");
            
            #line 222 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\t\t\t\t\r\n\t\t\t\t<td>\r\n\t\t\t\t\tHatch Cycles\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 228 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HatchCycles));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tBase Friendship\r\n\t\t\t\t</td>\r\n\t\t\t\t<t" +
                    "d>\r\n\t\t\t\t\t");
            
            #line 236 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseFriendship));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\t\t\t\t\r\n\t\t\t\t<td>\r\n\t\t\t\t\tExp Growth\r\n\t\t\t\t</td>\r\n\t\t\t\t<td" +
                    ">\r\n\t\t\t\t\t");
            
            #line 244 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ExpGrowth));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\t\t\t\t\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tForme Count\r\n\t\t\t\t</td>\r\n\t\t\t\t<t" +
                    "d>\r\n\t\t\t\t\t");
            
            #line 252 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.FormeCount));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tForme Sprite\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r" +
                    "\n\t\t\t\t\t");
            
            #line 260 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.FormeSprite));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tColor\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t");
            
            #line 268 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Color));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tBase Exp\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t" +
                    "\t\t");
            
            #line 276 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseExp));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\t\t\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tEscape Rate\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>" +
                    "\r\n\t\t\t\t\t");
            
            #line 284 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EscapeRate));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tLocal Variant\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>" +
                    "\r\n\t\t\t\t\t");
            
            #line 292 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.LocalVariant));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 295 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.ZItem != null && Model.ZItem.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tZ Item\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$idPref" +
                    "ix-item-");
            
            #line 301 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZItem.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 301 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZItem.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 304 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 306 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.ZBaseMove != null && Model.ZBaseMove.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tZ Base Move\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$i" +
                    "dPrefix-move-");
            
            #line 312 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZBaseMove.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 312 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZBaseMove.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 315 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t");
            
            #line 317 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.ZMove != null && Model.ZMove.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\tZ Move\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<a href=\"{page=\"$idPref" +
                    "ix-move-");
            
            #line 323 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZMove.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 323 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZMove.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 326 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t</table>\r\n\t</div>\r\n\t<div class=\"col-md-3\">\r\n\t\t<h2>Stats</h2>\r\n\t\t<table class=\"" +
                    "table\">\r\n\t\t\t<tr>\r\n\t\t\t\t<td></td>\r\n\t\t\t\t<td>Base</td>\r\n\t\t\t\t<td>EV Yield</td>\r\n\t\t\t</" +
                    "tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>HP</td>\r\n\t\t\t\t<td>");
            
            #line 340 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseHP));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 341 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HPEVYield));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Attack</td>\r\n\t\t\t\t<td>");
            
            #line 345 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseAttack));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 346 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AttackEVYield));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Defense</td>\r\n\t\t\t\t<td>");
            
            #line 350 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseDefense));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 351 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DefenseEVYield));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Sp. Attack</td>\r\n\t\t\t\t<td>");
            
            #line 355 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseSpAttack));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 356 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SpAttackEVYield));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Sp. Defense</td>\r\n\t\t\t\t<td>");
            
            #line 360 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseSpDefense));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 361 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SpDefenseEVYield));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>Speed</td>\r\n\t\t\t\t<td>");
            
            #line 365 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseSpeed));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t\t<td>");
            
            #line 366 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SpeedEVYield));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t<tr>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<b>BST</b>\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t\t<b" +
                    ">");
            
            #line 373 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BST));
            
            #line default
            #line hidden
            this.Write("</b>\r\n\t\t\t\t</td>\r\n\t\t\t\t<td>\r\n\t\t\t\t</td>\r\n\t\t\t</tr>\t\r\n\t\t</table>\r\n\t\t<h2>Type Effective" +
                    "ness</h2>\r\n\t\t<table class=\"table\">\r\n\t\t\t");
            
            #line 381 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.TypeEffectiveness) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t<tr>\r\n\t\t\t\t<td><a href=\'{page=\"$idPrefix-type-");
            
            #line 383 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'><img alt=\"");
            
            #line 383 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 383 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a></td>\r\n\t\t\t\t<td>x");
            
            #line 384 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Multiplier));
            
            #line default
            #line hidden
            this.Write("</td>\r\n\t\t\t</tr>\r\n\t\t\t");
            
            #line 386 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</table>\r\n\t</div>\r\n</div>\r\n\r\n");
            
            #line 391 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.GetNonMegaAltForms().Any()) { 
            
            #line default
            #line hidden
            this.Write("<h2>Alternate Forms</h2>\r\n<table class=\"table\">\r\n\t<tr>\r\n\t\t<th style=\"width:60px;\"" +
                    "></th>\r\n        <th>Form</th>\r\n    </tr>\r\n\t");
            
            #line 398 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.GetNonMegaAltForms()) { 
            
            #line default
            #line hidden
            this.Write("\t<tr style=\"height:60px;vertical-align: middle;\">\r\n\t\t<td>\r\n\t\t\t<a href=\'{page=\"gen" +
                    "7-pkm-");
            
            #line 401 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 401 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\t\t\t\t\r\n\t\t</td>\r\n        <td>\r\n            <a href=\'{page=\"gen7-pkm-");
            
            #line 404 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 404 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n        </td>\r\n    </tr>\r\n\t");
            
            #line 407 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 409 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 411 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 var evolutionChain = Model.GetEvolutionChain(); 
            
            #line default
            #line hidden
            
            #line 412 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (evolutionChain.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h2>Evolution Chain</h2>\r\n<table class=\"table\">\r\n    <tr>\r\n\t\t<th style=\"width:60p" +
                    "x;\"></th>\r\n        <th>Target</th>\r\n\t\t<th>Method</th>\r\n    </tr>\r\n    ");
            
            #line 420 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in evolutionChain) { 
		string methodString;
		if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.PokemonReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"$idPrefix-pkm-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.MoveReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"$idPrefix-move-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.ItemReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"$idPrefix-item-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.TypeReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"$idPrefix-type-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (!string.IsNullOrEmpty(item.ParameterString)) {
			methodString = string.Format(item.Method, item.ParameterString);
		} 
		else {
			methodString = item.Method;
		} 
            
            #line default
            #line hidden
            this.Write("\t\r\n        <tr style=\"height:60px;vertical-align: middle;\">\r\n\t\t\t<td>\r\n\t\t\t\t<a href" +
                    "=\'{page=\"$idPrefix-pkm-");
            
            #line 443 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TargetPokemon.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 443 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TargetPokemon.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\t\t\t\t\r\n\t\t\t</td>\r\n            <td>\r\n                <a href=\'{page=\"$idPrefix-p" +
                    "km-");
            
            #line 446 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TargetPokemon.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 446 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TargetPokemon.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n\t\t\t<td>\r\n                ");
            
            #line 449 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodString));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 452 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 454 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 456 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveLevelUp.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h2>Moves (Level Up)</h2>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Level</th" +
                    ">\r\n        <th>Move</th>\r\n    </tr>\r\n    ");
            
            #line 463 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveLevelUp)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n                ");
            
            #line 467 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Level == 0 ? "With Evolution" : item.Level.ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"$idPrefix-move-");
            
            #line 470 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 470 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 473 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 475 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 477 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveTMs.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h2>Moves (TM)</h2>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Move</th>\r\n    " +
                    "</tr>\r\n    ");
            
            #line 483 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveTMs)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"$idPrefix-move-");
            
            #line 487 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 487 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 490 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 492 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 494 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveTutors.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h2>Moves (Tutor)</h2>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Move</th>\r\n " +
                    "   </tr>\r\n    ");
            
            #line 500 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveTutors)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"$idPrefix-move-");
            
            #line 504 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 504 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 507 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 509 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 511 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 var eggMoves = Model.GetEggMoves(); 
            
            #line default
            #line hidden
            
            #line 512 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (eggMoves.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h2>Moves (Egg)</h2>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Move</th>\r\n\t\t<" +
                    "th>Parents</th>\r\n    </tr>\r\n    ");
            
            #line 519 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in eggMoves)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"$idPrefix-move-");
            
            #line 523 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 523 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t");
            
            #line 524 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (item.RequiresChainBreeding(Model)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t(Requires chain breeding)\r\n\t\t\t\t");
            
            #line 526 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            </td>\r\n\t\t\t<td>\r\n\t\t\t\t");
            
            #line 529 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var parent in item.GetEggMoveSources(Model)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<a href=\"{page=\"$idPrefix-pkm-");
            
            #line 530 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parent.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 530 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parent.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t\t");
            
            #line 531 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n        </tr>\r\n    ");
            
            #line 534 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 536 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"

private global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class DetailsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
