// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectPokemon.Pokedex.Views.Gen7.Pokemon
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Details : DetailsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<h2>");
            
            #line 7 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("</h2>\r\n<h3>Details</h3>\r\n<dl class=\"dl-horizontal\">\r\n    <dt>\r\n        ID\r\n    </" +
                    "dt>\r\n    <dd>\r\n        ");
            
            #line 14 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ID));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Name\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 21 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base HP\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 28 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseHP));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Attack\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 35 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseAttack));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Defense\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 42 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseDefense));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Speed\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 49 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseSpeed));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Sp. Attack\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 56 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseSpAttack));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Sp. Defense\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 63 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseSpDefense));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        HP EV Yield\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 70 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HPEVYield));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Attack EV Yield\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 77 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AttackEVYield));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Defense EV Yield\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 84 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DefenseEVYield));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Speed EV Yield\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 91 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SpeedEVYield));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Sp. Attack EV Yield\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 98 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SpAttackEVYield));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Sp. Defense EV Yield\r\n    </dt>\r\n    <dd>\r\n        " +
                    "");
            
            #line 105 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.SpDefenseEVYield));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n\t\t");
            
            #line 109 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Type2.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("        Type\r\n\t\t");
            
            #line 111 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\tTypes\r\n\t\t");
            
            #line 113 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    </dt>\r\n    <dd>\r\n\t\t<a href=\"{page=\"type-");
            
            #line 116 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 116 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type1.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t");
            
            #line 117 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Type2.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t<a href=\"{page=\"type-");
            
            #line 118 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 118 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type2.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t");
            
            #line 119 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    </dd>\t\r\n\r\n\t<dt>\r\n        Catch Rate\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 126 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CatchRate));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Evo Stage\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 133 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EvoStage));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t");
            
            #line 136 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.HeldItem1.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t<dt>\r\n        Held Item 1\r\n    </dt>\r\n    <dd>\r\n        <a href=\"{page=\"item-");
            
            #line 141 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 141 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem1.Name));
            
            #line default
            #line hidden
            this.Write("</a> (50%)\r\n    </dd>\r\n\t");
            
            #line 143 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 145 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.HeldItem2.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t<dt>\r\n        Held Item 2\r\n    </dt>\r\n    <dd>\r\n        <a href=\"{page=\"item-");
            
            #line 150 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 150 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem2.Name));
            
            #line default
            #line hidden
            this.Write("</a> (5%)\r\n    </dd>\r\n\t");
            
            #line 152 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t");
            
            #line 154 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.HeldItem3.ID > 0) { 
            
            #line default
            #line hidden
            this.Write("\t<dt>\r\n        Held Item 3\r\n    </dt>\r\n    <dd>\r\n        <a href=\"{page=\"item-");
            
            #line 159 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem3.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 159 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HeldItem3.Name));
            
            #line default
            #line hidden
            this.Write("</a> (1%)\r\n    </dd>\r\n\t");
            
            #line 161 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\t<dt>\r\n        Gender\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 167 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Gender));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Hatch Cycles\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 174 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HatchCycles));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Friendship\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 181 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseFriendship));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Exp Growth\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 188 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ExpGrowth));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Egg Group 1\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 195 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EggGroup1));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Egg Group 2\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 202 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EggGroup2));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Ability 1\r\n    </dt>\r\n    <dd>\r\n        <a href=\"{p" +
                    "age=\"ability-");
            
            #line 209 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 209 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability1.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n    </dd>\r\n\r\n\t<dt>\r\n        Ability 2\r\n    </dt>\r\n    <dd>\r\n        <a href" +
                    "=\"{page=\"ability-");
            
            #line 216 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 216 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Ability2.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n    </dd>\r\n\r\n\t<dt>\r\n        Hidden Ability\r\n    </dt>\r\n    <dd>\r\n        <a" +
                    " href=\"{page=\"ability-");
            
            #line 223 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AbilityHidden.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 223 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.AbilityHidden.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n    </dd>\r\n\r\n\t<dt>\r\n        Forme Count\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 230 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.FormeCount));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Forme Sprite\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 237 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.FormeSprite));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Color\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 244 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Color));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Base Exp\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 251 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BaseExp));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        BST\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 258 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.BST));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        ID\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 265 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ID));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Height\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 272 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Height));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Weight\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 279 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Weight));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Escape Rate\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 286 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.EscapeRate));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Local Variant\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 293 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.LocalVariant));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Z Item\r\n    </dt>\r\n    <dd>\r\n        <a href=\"{page" +
                    "=\"item-");
            
            #line 300 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZItem.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 300 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZItem.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n    </dd>\r\n\r\n\t<dt>\r\n        Z Base Move\r\n    </dt>\r\n    <dd>\r\n        <a hr" +
                    "ef=\"{page=\"move-");
            
            #line 307 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZBaseMove.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 307 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZBaseMove.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n    </dd>\r\n\r\n\t<dt>\r\n        Z Move\r\n    </dt>\r\n    <dd>\r\n        <a href=\"{" +
                    "page=\"move-");
            
            #line 314 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZMove.ID));
            
            #line default
            #line hidden
            this.Write("\"}\">");
            
            #line 314 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ZMove.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n    </dd>\r\n\r\n</dl>\r\n\r\n");
            
            #line 319 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.Evolutions.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h3>Evolutions</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Target</th>\r\n  " +
                    "      <th>Level</th>\r\n\t\t<th>Form</th>\r\n\t\t<th>Method</th>\r\n    </tr>\r\n    ");
            
            #line 328 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.Evolutions) { 
		string methodString;
		if (item.ParameterReference == null) {
			methodString = item.Method;
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.PokemonReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"pkm-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.MoveReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"move-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.ItemReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"item-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else if (item.ParameterReference is ProjectPokemon.Pokedex.Models.Gen7.TypeReference) {
			methodString = string.Format(item.Method, "<a href='{page=\"type-" + item.ParameterReference.ID + "\"}'>" + item.ParameterReference.Name + "</a>");
		}
		else {
			methodString = item.Method;
		} 
            
            #line default
            #line hidden
            this.Write("\t\r\n        <tr>\r\n            <td>\r\n                <a href=\'{page=\"pkm-");
            
            #line 351 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TargetPokemon.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 351 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.TargetPokemon.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n\t\t\t<td>\r\n                ");
            
            #line 354 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Level));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n\t\t\t<td>\r\n                ");
            
            #line 357 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Form));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n\t\t\t<td>\r\n                ");
            
            #line 360 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodString));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 363 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 365 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 367 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveLevelUp.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h3>Moves (Level Up)</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Level</th" +
                    ">\r\n        <th>Move</th>\r\n    </tr>\r\n    ");
            
            #line 374 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveLevelUp)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n                ");
            
            #line 378 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Level));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"move-");
            
            #line 381 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 381 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 384 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 386 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 388 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveTMs.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h3>Moves (TM)</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Move</th>\r\n    " +
                    "</tr>\r\n    ");
            
            #line 394 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveTMs)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"move-");
            
            #line 398 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 398 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 401 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 403 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 405 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveEgg.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h3>Moves (Egg)</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Move</th>\r\n   " +
                    " </tr>\r\n    ");
            
            #line 411 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveEgg)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"move-");
            
            #line 415 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 415 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 418 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 420 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 422 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 if (Model.MoveTutors.Count > 0) { 
            
            #line default
            #line hidden
            this.Write("<h3>Moves (Tutor)</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n        <th>Move</th>\r\n " +
                    "   </tr>\r\n    ");
            
            #line 428 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 foreach (var item in Model.MoveTutors)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr>\r\n            <td>\r\n\t\t\t\t<a href=\'{page=\"move-");
            
            #line 432 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 432 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n            </td>\r\n        </tr>\r\n    ");
            
            #line 435 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 437 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Pokemon\Details.tt"

private global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::ProjectPokemon.Pokedex.Models.Gen7.Pokemon)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class DetailsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
