// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectPokemon.Pokedex.Views.Gen7.Moves
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class Details : DetailsBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<h3>Details</h3>\r\n<dl class=\"dl-horizontal\">\r\n    <dt>\r\n        ID\r\n    </dt>\r\n  " +
                    "  <dd>\r\n        ");
            
            #line 13 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ID));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Name\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 20 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Description\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 27 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Description));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Type\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 34 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Type));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Qualities\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 41 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Qualities));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Category\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 48 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Category));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Power\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 55 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Power));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Accuracy\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 62 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Accuracy));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        PP\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 69 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.PP));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Priority\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 76 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Priority));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        HitMin\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 83 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HitMin));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        HitMax\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 90 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.HitMax));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Inflict\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 97 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Inflict));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        InflictChance\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 104 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.InflictChance));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        TurnMin\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 111 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.TurnMin));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        TurnMax\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 118 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.TurnMax));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        CritStage\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 125 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.CritStage));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Flinch\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 132 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Flinch));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Effect\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 139 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Effect));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Recoil\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 146 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Recoil));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Heal\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 153 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Heal));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Targeting\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 160 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Targeting));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat1\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 167 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat1));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat2\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 174 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat2));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat3\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 181 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat3));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat1Num\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 188 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat1Num));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat2Num\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 195 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat2Num));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat3Num\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 202 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat3Num));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat1Percent\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 209 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat1Percent));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat2Percent\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 216 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat2Percent));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\r\n\t<dt>\r\n        Stat3Percent\r\n    </dt>\r\n    <dd>\r\n        ");
            
            #line 223 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Stat3Percent));
            
            #line default
            #line hidden
            this.Write("\r\n    </dd>\r\n\t\r\n</dl>\r\n\r\n");
            
            #line 228 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (Model.PokemonThroughLevelUp.Any()) { 
            
            #line default
            #line hidden
            this.Write("<h3>Pokémon Through Level-Up</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n\t\t<th style=\"" +
                    "width:60px;\">Dex ID</th>\r\n\t\t<th style=\"width:60px;\">Icon</th>\r\n        <th>Name<" +
                    "/th>\r\n\t\t<th>Type</th>\r\n\t\t<th>Ability</th>\r\n        <th>Level(s)</th>\r\n    </tr>\r" +
                    "\n    ");
            
            #line 239 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 foreach (var item in Model.PokemonThroughLevelUp)
    { 
            
            #line default
            #line hidden
            this.Write("\t\t<tr style=\"height:60px;\">\t\t\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t");
            
            #line 243 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"$idPrefi" +
                    "x-pkm-");
            
            #line 246 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 246 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\t\t\t\t\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"" +
                    "$idPrefix-pkm-");
            
            #line 249 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 249 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\"{page=\"$idP" +
                    "refix-type-");
            
            #line 252 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 252 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 252 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 253 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Type2.ID > 0 && item.Type1.ID != item.Type2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<a href=\"{page=\"$idPrefix-type-");
            
            #line 254 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 254 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 254 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 255 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<span>");
            
            #line 258 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability1.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\r\n\t\t\t\t");
            
            #line 260 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Ability1.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 261 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability2.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 262 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 263 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.AbilityHidden.ID != item.Ability1.ID && item.AbilityHidden.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 264 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.AbilityHidden.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 265 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n                ");
            
            #line 268 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", item.Levels)));
            
            #line default
            #line hidden
            this.Write("\r\n            </td>\r\n\t\t</tr>\r\n    ");
            
            #line 271 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 273 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 275 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (Model.PokemonThroughTM.Any()) { 
            
            #line default
            #line hidden
            this.Write("<h3>Pokémon Through TM</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n\t\t<th style=\"width:" +
                    "60px;\">Dex ID</th>\r\n\t\t<th style=\"width:60px;\">Icon</th>\r\n        <th>Name</th>\r\n" +
                    "\t\t<th>Type</th>\r\n\t\t<th>Ability</th>\r\n    </tr>\r\n    ");
            
            #line 285 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 foreach (var item in Model.PokemonThroughTM)
    { 
            
            #line default
            #line hidden
            this.Write("\t\t<tr style=\"height:60px;\">\t\t\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t");
            
            #line 289 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"$idPrefi" +
                    "x-pkm-");
            
            #line 292 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 292 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\t\t\t\t\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"" +
                    "$idPrefix-pkm-");
            
            #line 295 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 295 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\"{page=\"$idP" +
                    "refix-type-");
            
            #line 298 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 298 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 298 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 299 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Type2.ID > 0 && item.Type1.ID != item.Type2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<a href=\"{page=\"$idPrefix-type-");
            
            #line 300 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 300 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 300 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 301 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<span>");
            
            #line 304 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability1.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\r\n\t\t\t\t");
            
            #line 306 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Ability1.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 307 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability2.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 308 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 309 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.AbilityHidden.ID != item.Ability1.ID && item.AbilityHidden.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 310 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.AbilityHidden.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 311 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t</tr>\r\n    ");
            
            #line 314 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 316 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 318 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (Model.PokemonThroughEgg.Any()) { 
            
            #line default
            #line hidden
            this.Write("<h3>Pokémon Through Egg</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n\t\t<th style=\"width" +
                    ":60px;\">Dex ID</th>\r\n\t\t<th style=\"width:60px;\">Icon</th>\r\n        <th>Name</th>\r" +
                    "\n\t\t<th>Type</th>\r\n\t\t<th>Ability</th>\r\n    </tr>\r\n    ");
            
            #line 328 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 foreach (var item in Model.PokemonThroughEgg)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr style=\"height:60px;\">\t\t\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t" +
                    "\t");
            
            #line 332 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"$idPrefi" +
                    "x-pkm-");
            
            #line 335 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 335 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\t\t\t\t\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"" +
                    "$idPrefix-pkm-");
            
            #line 338 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 338 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\"{page=\"$idP" +
                    "refix-type-");
            
            #line 341 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 341 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 341 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 342 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Type2.ID > 0 && item.Type1.ID != item.Type2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<a href=\"{page=\"$idPrefix-type-");
            
            #line 343 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 343 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 343 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 344 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<span>");
            
            #line 347 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability1.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\r\n\t\t\t\t");
            
            #line 349 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Ability1.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 350 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability2.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 351 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 352 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.AbilityHidden.ID != item.Ability1.ID && item.AbilityHidden.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 353 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.AbilityHidden.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 354 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t</tr>\r\n    ");
            
            #line 357 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 359 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 361 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (Model.PokemonThroughTutor.Any()) { 
            
            #line default
            #line hidden
            this.Write("<h3>Pokémon Through Tutor</h3>\r\n<table class=\"table\">\r\n    <tr>\r\n\t\t<th style=\"wid" +
                    "th:60px;\">Dex ID</th>\r\n\t\t<th style=\"width:60px;\">Icon</th>\r\n        <th>Name</th" +
                    ">\r\n\t\t<th>Type</th>\r\n\t\t<th>Ability</th>\r\n    </tr>\r\n    ");
            
            #line 371 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 foreach (var item in Model.PokemonThroughTutor)
    { 
            
            #line default
            #line hidden
            this.Write("        <tr style=\"height:60px;\">\t\t\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t" +
                    "\t");
            
            #line 375 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"$idPrefi" +
                    "x-pkm-");
            
            #line 378 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 378 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.PokespriteHtml));
            
            #line default
            #line hidden
            this.Write("</a>\t\t\t\t\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\'{page=\"" +
                    "$idPrefix-pkm-");
            
            #line 381 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ID));
            
            #line default
            #line hidden
            this.Write("\"}\'>");
            
            #line 381 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("</a>\r\n\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<a href=\"{page=\"$idP" +
                    "refix-type-");
            
            #line 384 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 384 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 384 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type1.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 385 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Type2.ID > 0 && item.Type1.ID != item.Type2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<a href=\"{page=\"$idPrefix-type-");
            
            #line 386 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.ID));
            
            #line default
            #line hidden
            this.Write("\"}\"><img alt=\"");
            
            #line 386 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write("\" src=\"https://projectpokemon.org/images/gen7-types/");
            
            #line 386 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Type2.Name));
            
            #line default
            #line hidden
            this.Write(".png\" /></a>\r\n\t\t\t\t");
            
            #line 387 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t\t<td style=\"vertical-align: middle;\">\r\n\t\t\t\t<span>");
            
            #line 390 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability1.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\r\n\t\t\t\t");
            
            #line 392 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.Ability1.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 393 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Ability2.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 394 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 395 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 if (item.AbilityHidden.ID != item.Ability1.ID && item.AbilityHidden.ID != item.Ability2.ID) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t<br /><span>");
            
            #line 396 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.AbilityHidden.Name));
            
            #line default
            #line hidden
            this.Write("</span>\r\n\t\t\t\t");
            
            #line 397 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t</td>\r\n\t\t</tr>\r\n    ");
            
            #line 400 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            this.Write("</table>\r\n");
            
            #line 402 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Users\evanl\Git\Project-Pokemon-Pokedex\Project Pokemon Pokedex\Views\Gen7\Moves\Details.tt"

private global::ProjectPokemon.Pokedex.Models.Gen7.Move _ModelField;

/// <summary>
/// Access the Model parameter of the template.
/// </summary>
private global::ProjectPokemon.Pokedex.Models.Gen7.Move Model
{
    get
    {
        return this._ModelField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool ModelValueAcquired = false;
if (this.Session.ContainsKey("Model"))
{
    this._ModelField = ((global::ProjectPokemon.Pokedex.Models.Gen7.Move)(this.Session["Model"]));
    ModelValueAcquired = true;
}
if ((ModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Model");
    if ((data != null))
    {
        this._ModelField = ((global::ProjectPokemon.Pokedex.Models.Gen7.Move)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class DetailsBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
